import { createServerFn } from '@tanstack/react-start'
import { eq } from '@kurama/data-ops/database/drizzle-orm'
import { lessons, subjects, cards } from '@kurama/data-ops/drizzle/schema'
import { adminMiddleware } from '../middleware/admin-auth'
import { initAdminDb, getDb } from '@/lib/db'
import {
  generateTeachPlanSchema,
  generateCardsSchema,
  saveGeneratedCardsSchema,
  type GenerateTeachPlanInput,
  type GenerateCardsInput,
  type SaveGeneratedCardsInput,
} from '@/lib/schemas'
import {
  generateLessonPlan,
  generateCompleteCards,
} from '@/lib/ai/gemini-client'

// Get API key from environment
function getGeminiApiKey(): string {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY non configurée. Veuillez ajouter la clé API dans les variables d\'environnement.')
  }
  return apiKey
}

// Generate teach plan for a lesson
export const generateTeachPlan = createServerFn({ method: 'POST' })
  .middleware([adminMiddleware])
  .inputValidator((data: GenerateTeachPlanInput) => generateTeachPlanSchema.parse(data))
  .handler(async ({ data, context }) => {
    initAdminDb()
    const db = getDb()
    const apiKey = getGeminiApiKey()

    // Get lesson with subject info
    const lessonResult = await db
      .select({
        id: lessons.id,
        title: lessons.title,
        subjectName: subjects.name,
      })
      .from(lessons)
      .leftJoin(subjects, eq(lessons.subjectId, subjects.id))
      .where(eq(lessons.id, data.lessonId))
      .limit(1)

    const lesson = lessonResult[0]
    if (!lesson) {
      throw new Error('Leçon non trouvée')
    }

    // Generate lesson plan using AI
    const result = await generateLessonPlan(apiKey, {
      country: data.country,
      subject: lesson.subjectName || 'Matière',
      grade: data.grade,
      language: data.language,
      schoolYear: data.schoolYear,
      lessonTitle: lesson.title,
      customInstructions: data.customInstructions,
    })

    // Save to database
    const metadata = {
      country: data.country,
      grade: data.grade,
      language: data.language,
      sources: result.sources,
      generatedBy: 'gemini-2.5-flash',
    }

    const updateResult = await db
      .update(lessons)
      .set({
        teachPlan: result.content,
        teachPlanGeneratedAt: new Date().toISOString(),
        teachPlanMetadata: metadata,
        updatedAt: new Date().toISOString(),
      })
      .where(eq(lessons.id, data.lessonId))
      .returning({
        id: lessons.id,
        teachPlan: lessons.teachPlan,
        teachPlanGeneratedAt: lessons.teachPlanGeneratedAt,
        teachPlanMetadata: lessons.teachPlanMetadata,
      })

    const updated = updateResult[0]
    console.log(`[AUDIT] Teach plan generated by ${context.email} for lesson:`, data.lessonId)

    return {
      success: true,
      lesson: updated,
      sources: result.sources,
    }
  })

// Generate complete cards from teach plan (flashcard + quiz in one)
export const generateCardsFromPlan = createServerFn({ method: 'POST' })
  .middleware([adminMiddleware])
  .inputValidator((data: GenerateCardsInput) => generateCardsSchema.parse(data))
  .handler(async ({ data }) => {
    initAdminDb()
    const db = getDb()
    const apiKey = getGeminiApiKey()

    // Get lesson with teach plan
    const lessonResult = await db
      .select({
        id: lessons.id,
        title: lessons.title,
        teachPlan: lessons.teachPlan,
      })
      .from(lessons)
      .where(eq(lessons.id, data.lessonId))
      .limit(1)

    const lesson = lessonResult[0]
    if (!lesson) {
      throw new Error('Leçon non trouvée')
    }

    if (!lesson.teachPlan) {
      throw new Error('Cette leçon n\'a pas de plan d\'enseignement. Veuillez d\'abord générer un plan.')
    }

    // Generate complete cards (flashcard + quiz combined)
    const completeCards = await generateCompleteCards(apiKey, lesson.teachPlan, data.amount)

    return {
      success: true,
      cards: completeCards.map((card, index) => ({
        lessonId: data.lessonId,
        cardType: 'multichoice' as const, // Use multichoice to store all data
        frontContent: card.frontContent,
        backContent: card.backContent,
        question: card.question,
        options: card.options,
        correctAnswer: card.options.find(o => o.isCorrect)?.text || '',
        explanation: card.explanation,
        hints: card.hints,
        displayOrder: index + 1,
        points: 10,
        difficulty: 0,
      })),
    }
  })

// Save generated cards to database
export const saveGeneratedCards = createServerFn({ method: 'POST' })
  .middleware([adminMiddleware])
  .inputValidator((data: SaveGeneratedCardsInput) => saveGeneratedCardsSchema.parse(data))
  .handler(async ({ data, context }) => {
    initAdminDb()
    const db = getDb()

    // Get current max display order for this lesson
    const maxOrderResult = await db
      .select({ max: cards.displayOrder })
      .from(cards)
      .where(eq(cards.lessonId, data.lessonId))
      .orderBy(cards.displayOrder)
      .limit(1)

    let startOrder = (maxOrderResult[0]?.max || 0) + 1

    // Insert all cards
    const insertedCards: Array<{
      id: number
      lessonId: number
      cardType: string
      frontContent: string
      backContent: string
    }> = []

    for (const card of data.cards) {
      const result = await db
        .insert(cards)
        .values({
          ...card,
          displayOrder: startOrder++,
        })
        .returning({
          id: cards.id,
          lessonId: cards.lessonId,
          cardType: cards.cardType,
          frontContent: cards.frontContent,
          backContent: cards.backContent,
        })

      if (result[0]) {
        insertedCards.push(result[0])
      }
    }

    console.log(`[AUDIT] ${insertedCards.length} cards saved by ${context.email} for lesson:`, data.lessonId)

    return {
      success: true,
      savedCount: insertedCards.length,
    }
  })

// Update teach plan manually
export const updateTeachPlan = createServerFn({ method: 'POST' })
  .middleware([adminMiddleware])
  .inputValidator((data: { lessonId: number; teachPlan: string }) => data)
  .handler(async ({ data, context }) => {
    initAdminDb()
    const db = getDb()

    const result = await db
      .update(lessons)
      .set({
        teachPlan: data.teachPlan,
        updatedAt: new Date().toISOString(),
      })
      .where(eq(lessons.id, data.lessonId))
      .returning({
        id: lessons.id,
        teachPlan: lessons.teachPlan,
      })

    const updated = result[0]
    if (!updated) {
      throw new Error('Leçon non trouvée')
    }

    console.log(`[AUDIT] Teach plan updated manually by ${context.email} for lesson:`, data.lessonId)

    return { success: true, lesson: updated }
  })
