/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppProgressRouteImport } from './routes/_auth/app/progress'
import { Route as AuthAppProfileRouteImport } from './routes/_auth/app/profile'
import { Route as AuthAppGroupsRouteImport } from './routes/_auth/app/groups'
import { Route as AuthAppSubjectsIndexRouteImport } from './routes/_auth/app/subjects.index'
import { Route as AuthAppTestSummaryLessonIdRouteImport } from './routes/_auth/app/test-summary.$lessonId'
import { Route as AuthAppSubjectsSubjectIdRouteImport } from './routes/_auth/app/subjects.$subjectId'
import { Route as AuthAppPolarSubscriptionsRouteImport } from './routes/_auth/app/polar/subscriptions'
import { Route as AuthAppPolarPortalRouteImport } from './routes/_auth/app/polar/portal'
import { Route as AuthAppLessonsLessonIdRouteImport } from './routes/_auth/app/lessons.$lessonId'
import { Route as AuthAppLessonSummaryLessonIdRouteImport } from './routes/_auth/app/lesson-summary.$lessonId'
import { Route as AuthAppLessonSessionLessonIdRouteImport } from './routes/_auth/app/lesson-session.$lessonId'
import { Route as AuthAppPolarCheckoutSuccessRouteImport } from './routes/_auth/app/polar/checkout.success'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/app/index.lazy').then((d) => d.Route),
)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppProgressRoute = AuthAppProgressRouteImport.update({
  id: '/app/progress',
  path: '/app/progress',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppProfileRoute = AuthAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppGroupsRoute = AuthAppGroupsRouteImport.update({
  id: '/app/groups',
  path: '/app/groups',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppSubjectsIndexRoute = AuthAppSubjectsIndexRouteImport.update({
  id: '/app/subjects/',
  path: '/app/subjects/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppTestSummaryLessonIdRoute =
  AuthAppTestSummaryLessonIdRouteImport.update({
    id: '/app/test-summary/$lessonId',
    path: '/app/test-summary/$lessonId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppSubjectsSubjectIdRoute =
  AuthAppSubjectsSubjectIdRouteImport.update({
    id: '/app/subjects/$subjectId',
    path: '/app/subjects/$subjectId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppPolarSubscriptionsRoute =
  AuthAppPolarSubscriptionsRouteImport.update({
    id: '/app/polar/subscriptions',
    path: '/app/polar/subscriptions',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppPolarPortalRoute = AuthAppPolarPortalRouteImport.update({
  id: '/app/polar/portal',
  path: '/app/polar/portal',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppLessonsLessonIdRoute = AuthAppLessonsLessonIdRouteImport.update({
  id: '/app/lessons/$lessonId',
  path: '/app/lessons/$lessonId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppLessonSummaryLessonIdRoute =
  AuthAppLessonSummaryLessonIdRouteImport.update({
    id: '/app/lesson-summary/$lessonId',
    path: '/app/lesson-summary/$lessonId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppLessonSessionLessonIdRoute =
  AuthAppLessonSessionLessonIdRouteImport.update({
    id: '/app/lesson-session/$lessonId',
    path: '/app/lesson-session/$lessonId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppPolarCheckoutSuccessRoute =
  AuthAppPolarCheckoutSuccessRouteImport.update({
    id: '/app/polar/checkout/success',
    path: '/app/polar/checkout/success',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/app/groups': typeof AuthAppGroupsRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/progress': typeof AuthAppProgressRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/lesson-session/$lessonId': typeof AuthAppLessonSessionLessonIdRoute
  '/app/lesson-summary/$lessonId': typeof AuthAppLessonSummaryLessonIdRoute
  '/app/lessons/$lessonId': typeof AuthAppLessonsLessonIdRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/app/subjects/$subjectId': typeof AuthAppSubjectsSubjectIdRoute
  '/app/test-summary/$lessonId': typeof AuthAppTestSummaryLessonIdRoute
  '/app/subjects': typeof AuthAppSubjectsIndexRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/app/groups': typeof AuthAppGroupsRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/progress': typeof AuthAppProgressRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/lesson-session/$lessonId': typeof AuthAppLessonSessionLessonIdRoute
  '/app/lesson-summary/$lessonId': typeof AuthAppLessonSummaryLessonIdRoute
  '/app/lessons/$lessonId': typeof AuthAppLessonsLessonIdRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/app/subjects/$subjectId': typeof AuthAppSubjectsSubjectIdRoute
  '/app/test-summary/$lessonId': typeof AuthAppTestSummaryLessonIdRoute
  '/app/subjects': typeof AuthAppSubjectsIndexRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/_auth/app/groups': typeof AuthAppGroupsRoute
  '/_auth/app/profile': typeof AuthAppProfileRoute
  '/_auth/app/progress': typeof AuthAppProgressRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/lesson-session/$lessonId': typeof AuthAppLessonSessionLessonIdRoute
  '/_auth/app/lesson-summary/$lessonId': typeof AuthAppLessonSummaryLessonIdRoute
  '/_auth/app/lessons/$lessonId': typeof AuthAppLessonsLessonIdRoute
  '/_auth/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/_auth/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/_auth/app/subjects/$subjectId': typeof AuthAppSubjectsSubjectIdRoute
  '/_auth/app/test-summary/$lessonId': typeof AuthAppTestSummaryLessonIdRoute
  '/_auth/app/subjects/': typeof AuthAppSubjectsIndexRoute
  '/_auth/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/api/health'
    | '/api/metrics'
    | '/app/groups'
    | '/app/profile'
    | '/app/progress'
    | '/api/auth/$'
    | '/app'
    | '/app/lesson-session/$lessonId'
    | '/app/lesson-summary/$lessonId'
    | '/app/lessons/$lessonId'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/app/subjects/$subjectId'
    | '/app/test-summary/$lessonId'
    | '/app/subjects'
    | '/app/polar/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/api/health'
    | '/api/metrics'
    | '/app/groups'
    | '/app/profile'
    | '/app/progress'
    | '/api/auth/$'
    | '/app'
    | '/app/lesson-session/$lessonId'
    | '/app/lesson-summary/$lessonId'
    | '/app/lessons/$lessonId'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/app/subjects/$subjectId'
    | '/app/test-summary/$lessonId'
    | '/app/subjects'
    | '/app/polar/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/onboarding'
    | '/api/health'
    | '/api/metrics'
    | '/_auth/app/groups'
    | '/_auth/app/profile'
    | '/_auth/app/progress'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/lesson-session/$lessonId'
    | '/_auth/app/lesson-summary/$lessonId'
    | '/_auth/app/lessons/$lessonId'
    | '/_auth/app/polar/portal'
    | '/_auth/app/polar/subscriptions'
    | '/_auth/app/subjects/$subjectId'
    | '/_auth/app/test-summary/$lessonId'
    | '/_auth/app/subjects/'
    | '/_auth/app/polar/checkout/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/progress': {
      id: '/_auth/app/progress'
      path: '/app/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AuthAppProgressRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/profile': {
      id: '/_auth/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthAppProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/groups': {
      id: '/_auth/app/groups'
      path: '/app/groups'
      fullPath: '/app/groups'
      preLoaderRoute: typeof AuthAppGroupsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/subjects/': {
      id: '/_auth/app/subjects/'
      path: '/app/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AuthAppSubjectsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/test-summary/$lessonId': {
      id: '/_auth/app/test-summary/$lessonId'
      path: '/app/test-summary/$lessonId'
      fullPath: '/app/test-summary/$lessonId'
      preLoaderRoute: typeof AuthAppTestSummaryLessonIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/subjects/$subjectId': {
      id: '/_auth/app/subjects/$subjectId'
      path: '/app/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId'
      preLoaderRoute: typeof AuthAppSubjectsSubjectIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/subscriptions': {
      id: '/_auth/app/polar/subscriptions'
      path: '/app/polar/subscriptions'
      fullPath: '/app/polar/subscriptions'
      preLoaderRoute: typeof AuthAppPolarSubscriptionsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/portal': {
      id: '/_auth/app/polar/portal'
      path: '/app/polar/portal'
      fullPath: '/app/polar/portal'
      preLoaderRoute: typeof AuthAppPolarPortalRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/lessons/$lessonId': {
      id: '/_auth/app/lessons/$lessonId'
      path: '/app/lessons/$lessonId'
      fullPath: '/app/lessons/$lessonId'
      preLoaderRoute: typeof AuthAppLessonsLessonIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/lesson-summary/$lessonId': {
      id: '/_auth/app/lesson-summary/$lessonId'
      path: '/app/lesson-summary/$lessonId'
      fullPath: '/app/lesson-summary/$lessonId'
      preLoaderRoute: typeof AuthAppLessonSummaryLessonIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/lesson-session/$lessonId': {
      id: '/_auth/app/lesson-session/$lessonId'
      path: '/app/lesson-session/$lessonId'
      fullPath: '/app/lesson-session/$lessonId'
      preLoaderRoute: typeof AuthAppLessonSessionLessonIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/checkout/success': {
      id: '/_auth/app/polar/checkout/success'
      path: '/app/polar/checkout/success'
      fullPath: '/app/polar/checkout/success'
      preLoaderRoute: typeof AuthAppPolarCheckoutSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppGroupsRoute: typeof AuthAppGroupsRoute
  AuthAppProfileRoute: typeof AuthAppProfileRoute
  AuthAppProgressRoute: typeof AuthAppProgressRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppLessonSessionLessonIdRoute: typeof AuthAppLessonSessionLessonIdRoute
  AuthAppLessonSummaryLessonIdRoute: typeof AuthAppLessonSummaryLessonIdRoute
  AuthAppLessonsLessonIdRoute: typeof AuthAppLessonsLessonIdRoute
  AuthAppPolarPortalRoute: typeof AuthAppPolarPortalRoute
  AuthAppPolarSubscriptionsRoute: typeof AuthAppPolarSubscriptionsRoute
  AuthAppSubjectsSubjectIdRoute: typeof AuthAppSubjectsSubjectIdRoute
  AuthAppTestSummaryLessonIdRoute: typeof AuthAppTestSummaryLessonIdRoute
  AuthAppSubjectsIndexRoute: typeof AuthAppSubjectsIndexRoute
  AuthAppPolarCheckoutSuccessRoute: typeof AuthAppPolarCheckoutSuccessRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppGroupsRoute: AuthAppGroupsRoute,
  AuthAppProfileRoute: AuthAppProfileRoute,
  AuthAppProgressRoute: AuthAppProgressRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppLessonSessionLessonIdRoute: AuthAppLessonSessionLessonIdRoute,
  AuthAppLessonSummaryLessonIdRoute: AuthAppLessonSummaryLessonIdRoute,
  AuthAppLessonsLessonIdRoute: AuthAppLessonsLessonIdRoute,
  AuthAppPolarPortalRoute: AuthAppPolarPortalRoute,
  AuthAppPolarSubscriptionsRoute: AuthAppPolarSubscriptionsRoute,
  AuthAppSubjectsSubjectIdRoute: AuthAppSubjectsSubjectIdRoute,
  AuthAppTestSummaryLessonIdRoute: AuthAppTestSummaryLessonIdRoute,
  AuthAppSubjectsIndexRoute: AuthAppSubjectsIndexRoute,
  AuthAppPolarCheckoutSuccessRoute: AuthAppPolarCheckoutSuccessRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
