/// <reference lib="webworker" />

import type { ManifestEntry } from 'workbox-build'
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'

// Declare service worker scope with Workbox types
declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: ManifestEntry[]
}

// Declare SyncEvent interface for Background Sync API
interface SyncEvent extends ExtendableEvent {
  tag: string
  lastChance: boolean
}

/**
 * Kurama Service Worker
 * Handles offline functionality and caching strategies
 */

// Precache all assets generated by Vite PWA plugin
// The __WB_MANIFEST is replaced by workbox-build with the list of assets to precache
precacheAndRoute(self.__WB_MANIFEST)

// Take control of all clients immediately
// This ensures the service worker activates and takes control without waiting
self.skipWaiting()
clientsClaim()

/**
 * Service Worker Installation
 * Triggered when the service worker is first installed
 */
self.addEventListener('install', (event) => {
  console.log('[SW] Service Worker installing...')

  // Force the waiting service worker to become the active service worker
  event.waitUntil(self.skipWaiting())
})

/**
 * Service Worker Activation
 * Triggered when the service worker becomes active
 */
self.addEventListener('activate', (event) => {
  console.log('[SW] Service Worker activating...')

  event.waitUntil(
    Promise.all([
      // Take control of all clients immediately
      self.clients.claim(),
      // Clean up old caches if needed
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter((cacheName) => {
              // Remove old cache versions
              // Keep caches that match our naming pattern
              return !cacheName.startsWith('kurama-')
            })
            .map(cacheName => caches.delete(cacheName)),
        )
      }),
    ]),
  )
})

/**
 * Service Worker Fetch Handler
 * Intercepts all network requests
 */
self.addEventListener('fetch', (event) => {
  const { request } = event
  const url = new URL(request.url)

  // Skip cross-origin requests
  if (url.origin !== self.location.origin) {
    return
  }

  // Let Workbox handle precached assets
  // For other requests, use network-first strategy
  event.respondWith(
    caches.match(request).then((cachedResponse) => {
      if (cachedResponse) {
        // Return cached response and update cache in background
        fetch(request)
          .then((response) => {
            if (response && response.status === 200) {
              const responseToCache = response.clone()
              caches.open('kurama-runtime').then((cache) => {
                cache.put(request, responseToCache)
              })
            }
          })
          .catch(() => {
            // Network request failed, but we have cache
          })
        return cachedResponse
      }

      // No cache, fetch from network
      return fetch(request)
        .then((response) => {
          // Cache successful responses
          if (response && response.status === 200) {
            const responseToCache = response.clone()
            caches.open('kurama-runtime').then((cache) => {
              cache.put(request, responseToCache)
            })
          }
          return response
        })
        .catch(() => {
          // Network request failed and no cache
          // Return offline page for navigation requests
          if (request.mode === 'navigate') {
            return caches.match('/offline.html').then((offlineResponse) => {
              return (
                offlineResponse
                || new Response('Offline - No cached content available', {
                  status: 503,
                  statusText: 'Service Unavailable',
                  headers: new Headers({
                    'Content-Type': 'text/plain',
                  }),
                })
              )
            })
          }
          throw new Error('Network request failed and no cache available')
        })
    }),
  )
})

/**
 * Service Worker Message Handler
 * Handles messages from the client
 */
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // Force update when requested
    self.skipWaiting()
  }

  if (event.data && event.data.type === 'CACHE_URLS') {
    // Cache specific URLs on demand
    const urls = event.data.urls as string[]
    event.waitUntil(
      caches.open('kurama-runtime').then((cache) => {
        return cache.addAll(urls)
      }),
    )
  }

  if (event.data && event.data.type === 'CLEAR_CACHE') {
    // Clear all caches
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames.map(cacheName => caches.delete(cacheName)),
        )
      }),
    )
  }
})

/**
 * Background Sync Handler
 * Handles background sync events for offline mutations
 */
self.addEventListener('sync', (event: Event) => {
  const syncEvent = event as SyncEvent
  if (syncEvent.tag === 'sync-mutations') {
    console.log('[SW] Background sync: sync-mutations')

    syncEvent.waitUntil(
      // Notify clients to process mutation queue
      self.clients.matchAll().then((clients) => {
        clients.forEach((client) => {
          client.postMessage({
            type: 'SYNC_MUTATIONS',
          })
        })
      }),
    )
  }
})

/**
 * Push Notification Handler (for future use)
 */
self.addEventListener('push', (event) => {
  if (!event.data)
    return

  const data = event.data.json()
  const title = data.title || 'Kurama'
  const options = {
    body: data.body || '',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    data: data.data || {},
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

/**
 * Notification Click Handler
 */
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Focus existing window if available
        for (const client of clientList) {
          if ('focus' in client) {
            return client.focus()
          }
        }
        // Open new window if no existing window
        if (self.clients.openWindow) {
          return self.clients.openWindow('/')
        }
      }),
  )
})

console.log('[SW] Kurama Service Worker loaded')
