/// <reference lib="webworker" />

import type { ManifestEntry } from 'workbox-build'
import { clientsClaim } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute, setCatchHandler, setDefaultHandler } from 'workbox-routing'
import {
  CacheFirst,
  NetworkFirst,
  NetworkOnly,
  StaleWhileRevalidate,
} from 'workbox-strategies'

// Declare service worker scope with Workbox types
declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: ManifestEntry[]
}

// Declare SyncEvent interface for Background Sync API
interface SyncEvent extends ExtendableEvent {
  tag: string
  lastChance: boolean
}

/**
 * Kurama Service Worker
 * Handles offline functionality and caching strategies
 */

// Precache all assets generated by Vite PWA plugin
// The __WB_MANIFEST is replaced by workbox-build with the list of assets to precache
precacheAndRoute(self.__WB_MANIFEST)

// Take control of all clients immediately
// This ensures the service worker activates and takes control without waiting
self.skipWaiting()
clientsClaim()

/**
 * Service Worker Installation
 * Triggered when the service worker is first installed
 */
self.addEventListener('install', (event) => {
  console.log('[SW] Service Worker installing...')

  // Force the waiting service worker to become the active service worker
  event.waitUntil(self.skipWaiting())
})

/**
 * Service Worker Activation
 * Triggered when the service worker becomes active
 */
self.addEventListener('activate', (event) => {
  console.log('[SW] Service Worker activating...')

  event.waitUntil(
    Promise.all([
      // Take control of all clients immediately
      self.clients.claim(),
      // Clean up old caches if needed
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter((cacheName) => {
              // Remove old cache versions
              // Keep caches that match our naming pattern
              return !cacheName.startsWith('kurama-')
            })
            .map(cacheName => caches.delete(cacheName)),
        )
      }),
    ]),
  )
})

/**
 * Workbox Caching Strategies
 * Configure different caching strategies for different asset types
 */

// Cache names
const CACHE_NAMES = {
  STATIC: 'kurama-static-v1',
  IMAGES: 'kurama-images-v1',
  FONTS: 'kurama-fonts-v1',
  API: 'kurama-api-v1',
  RUNTIME: 'kurama-runtime-v1',
}

// 1. Cache JavaScript and CSS files with StaleWhileRevalidate
// Serves cached version immediately while fetching update in background
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: CACHE_NAMES.STATIC,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 60 * 60 * 24 * 90, // 90 days
        purgeOnQuotaError: true,
      }),
    ],
  }),
)

// 2. Cache images with CacheFirst strategy
// Serves from cache if available, otherwise fetches and caches
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: CACHE_NAMES.IMAGES,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        purgeOnQuotaError: true,
      }),
    ],
  }),
)

// 3. Cache fonts with CacheFirst strategy (fonts rarely change)
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: CACHE_NAMES.FONTS,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 365 days
        purgeOnQuotaError: true,
      }),
    ],
  }),
)

// 4. Cache Google Fonts stylesheets with StaleWhileRevalidate
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 365 days
      }),
    ],
  }),
)

// 5. Cache Google Fonts files with CacheFirst
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 365 days
      }),
    ],
  }),
)

// 6. Cache API calls with NetworkFirst strategy
// Tries network first, falls back to cache if offline
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: CACHE_NAMES.API,
    networkTimeoutSeconds: 3, // Fallback to cache after 3 seconds
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60, // 1 hour
        purgeOnQuotaError: true,
      }),
    ],
  }),
)

// 7. Default handler for other requests - NetworkOnly
setDefaultHandler(new NetworkOnly())

// 8. Catch handler for failed requests
// Provides offline fallback for navigation requests
setCatchHandler(async ({ request }) => {
  // Return offline page for navigation requests
  if (request.mode === 'navigate') {
    const response = await caches.match('/offline.html')
    return (
      response
      || new Response('Offline - No cached content available', {
        status: 503,
        statusText: 'Service Unavailable',
        headers: new Headers({
          'Content-Type': 'text/plain',
        }),
      })
    )
  }

  // For other requests, return a generic error
  return Response.error()
})

/**
 * Service Worker Message Handler
 * Handles messages from the client
 */
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // Force update when requested
    self.skipWaiting()
  }

  if (event.data && event.data.type === 'CACHE_URLS') {
    // Cache specific URLs on demand
    const urls = event.data.urls as string[]
    event.waitUntil(
      caches.open('kurama-runtime').then((cache) => {
        return cache.addAll(urls)
      }),
    )
  }

  if (event.data && event.data.type === 'CLEAR_CACHE') {
    // Clear all caches
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames.map(cacheName => caches.delete(cacheName)),
        )
      }),
    )
  }
})

/**
 * Background Sync Handler
 * Handles background sync events for offline mutations
 */
self.addEventListener('sync', (event: Event) => {
  const syncEvent = event as SyncEvent

  if (syncEvent.tag === 'sync-mutations') {
    console.log('[SW] Background sync: sync-mutations triggered')

    syncEvent.waitUntil(
      (async () => {
        try {
          // Notify all clients to process mutation queue
          const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' })

          if (clients.length === 0) {
            console.warn('[SW] No clients available to process mutations')
            return
          }

          // Send message to all clients
          const promises = clients.map((client) => {
            return new Promise<void>((resolve) => {
              const messageChannel = new MessageChannel()

              // Listen for response from client
              messageChannel.port1.onmessage = (event) => {
                if (event.data.success) {
                  console.log('[SW] Mutation sync completed successfully')
                } else {
                  console.error('[SW] Mutation sync failed:', event.data.error)
                }
                resolve()
              }

              // Send message with response port
              client.postMessage(
                {
                  type: 'SYNC_MUTATIONS',
                },
                [messageChannel.port2],
              )

              // Timeout after 30 seconds
              setTimeout(() => {
                console.warn('[SW] Mutation sync timeout')
                resolve()
              }, 30000)
            })
          })

          await Promise.all(promises)
          console.log('[SW] Background sync completed')
        } catch (error) {
          console.error('[SW] Background sync error:', error)
          // Re-throw to trigger retry
          throw error
        }
      })(),
    )
  }
})

/**
 * Push Notification Handler (for future use)
 */
self.addEventListener('push', (event) => {
  if (!event.data)
    return

  const data = event.data.json()
  const title = data.title || 'Kurama'
  const options = {
    body: data.body || '',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    data: data.data || {},
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

/**
 * Notification Click Handler
 */
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Focus existing window if available
        for (const client of clientList) {
          if ('focus' in client) {
            return client.focus()
          }
        }
        // Open new window if no existing window
        if (self.clients.openWindow) {
          return self.clients.openWindow('/')
        }
      }),
  )
})

console.log('[SW] Kurama Service Worker loaded')
