/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users.index'
import { Route as AdminSubjectsIndexRouteImport } from './routes/_admin/subjects.index'
import { Route as AdminLessonsIndexRouteImport } from './routes/_admin/lessons.index'
import { Route as AdminGradesIndexRouteImport } from './routes/_admin/grades.index'
import { Route as AdminCardsIndexRouteImport } from './routes/_admin/cards.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminLessonsLessonIdRouteImport } from './routes/_admin/lessons.$lessonId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsIndexRoute = AdminSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLessonsIndexRoute = AdminLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGradesIndexRoute = AdminGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCardsIndexRoute = AdminCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLessonsLessonIdRoute = AdminLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cards': typeof AdminCardsIndexRoute
  '/grades': typeof AdminGradesIndexRoute
  '/lessons': typeof AdminLessonsIndexRoute
  '/subjects': typeof AdminSubjectsIndexRoute
  '/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cards': typeof AdminCardsIndexRoute
  '/grades': typeof AdminGradesIndexRoute
  '/lessons': typeof AdminLessonsIndexRoute
  '/subjects': typeof AdminSubjectsIndexRoute
  '/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/cards/': typeof AdminCardsIndexRoute
  '/_admin/grades/': typeof AdminGradesIndexRoute
  '/_admin/lessons/': typeof AdminLessonsIndexRoute
  '/_admin/subjects/': typeof AdminSubjectsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/lessons/$lessonId'
    | '/api/auth/$'
    | '/cards'
    | '/grades'
    | '/lessons'
    | '/subjects'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/lessons/$lessonId'
    | '/api/auth/$'
    | '/cards'
    | '/grades'
    | '/lessons'
    | '/subjects'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/dashboard'
    | '/_admin/lessons/$lessonId'
    | '/api/auth/$'
    | '/_admin/cards/'
    | '/_admin/grades/'
    | '/_admin/lessons/'
    | '/_admin/subjects/'
    | '/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/subjects/': {
      id: '/_admin/subjects/'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AdminSubjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/lessons/': {
      id: '/_admin/lessons/'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AdminLessonsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/grades/': {
      id: '/_admin/grades/'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AdminGradesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/cards/': {
      id: '/_admin/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AdminCardsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/lessons/$lessonId': {
      id: '/_admin/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AdminLessonsLessonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLessonsLessonIdRoute: typeof AdminLessonsLessonIdRoute
  AdminCardsIndexRoute: typeof AdminCardsIndexRoute
  AdminGradesIndexRoute: typeof AdminGradesIndexRoute
  AdminLessonsIndexRoute: typeof AdminLessonsIndexRoute
  AdminSubjectsIndexRoute: typeof AdminSubjectsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLessonsLessonIdRoute: AdminLessonsLessonIdRoute,
  AdminCardsIndexRoute: AdminCardsIndexRoute,
  AdminGradesIndexRoute: AdminGradesIndexRoute,
  AdminLessonsIndexRoute: AdminLessonsIndexRoute,
  AdminSubjectsIndexRoute: AdminSubjectsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
