import type { GoogleGenAI } from '@google/genai'
import { z } from 'zod'
import { getGeminiModelName } from '../setup'

// Input schema for distractor generation
export const DistractorInputSchema = z.object({
  question: z.string().min(1, 'Question is required'),
  correctAnswer: z.string().min(1, 'Correct answer is required'),
  subject: z.string().min(1, 'Subject is required'),
  difficulty: z.number().int().min(0).max(2).default(1),
  cardType: z.string().default('basic'),
})

// Output schema for structured response
export const DistractorOutputSchema = z.object({
  distractors: z.array(z.string()).length(3),
  reasoning: z.string().optional(),
})

export type DistractorInput = z.infer<typeof DistractorInputSchema>
export type DistractorOutput = z.infer<typeof DistractorOutputSchema>

/**
 * Sanitize user input to prevent prompt injection attacks
 */
function sanitizeForPrompt(text: string, maxLength: number = 500): string {
  // Remove control characters (ASCII 0-31 and 127) using character class ranges
  // eslint-disable-next-line no-control-regex
  const controlCharsRegex = /[\u0000-\u001F\u007F]/g

  return text
    // Remove potential control characters
    .replace(controlCharsRegex, '')
    // Remove potential prompt injection markers
    .replace(/^(SYSTEM|USER|ASSISTANT|HUMAN|AI):/gim, '')
    // Limit consecutive newlines
    .replace(/\n{3,}/g, '\n\n')
    // Trim and limit length
    .trim()
    .slice(0, maxLength)
}

/**
 * Build the prompt for Gemini to generate distractors
 */
function buildPrompt(input: DistractorInput): string {
  const difficultyText = ['facile', 'moyen', 'difficile'][input.difficulty] || 'moyen'

  // Sanitize user inputs to prevent prompt injection
  const sanitizedQuestion = sanitizeForPrompt(input.question)
  const sanitizedAnswer = sanitizeForPrompt(input.correctAnswer, 200)
  const sanitizedSubject = sanitizeForPrompt(input.subject, 50)

  return `Tu es un expert en création de QCM éducatifs pour des étudiants ivoiriens préparant le BEPC/BAC.

CONTEXTE:
- Matière: ${sanitizedSubject}
- Niveau de difficulté: ${difficultyText}
- Type de carte: ${input.cardType}

QUESTION: ${sanitizedQuestion}
BONNE RÉPONSE: ${sanitizedAnswer}

TÂCHE:
Génère exactement 3 réponses FAUSSES mais PLAUSIBLES pour un QCM.

RÈGLES CRITIQUES:
1. Les réponses doivent être pertinentes pour la matière "${sanitizedSubject}"
2. Les réponses doivent sembler crédibles (pas évidemment fausses)
3. Les réponses doivent avoir une longueur similaire à la bonne réponse
4. Évite les réponses absurdes ou hors-sujet
5. Pour les matières scientifiques, utilise des erreurs conceptuelles courantes
6. Pour les langues, utilise des confusions grammaticales ou lexicales typiques
7. Pour l'histoire/géographie, utilise des dates/lieux proches mais incorrects
8. Assure-toi que les 3 réponses sont distinctes et différentes

EXEMPLES DE BONNES PRATIQUES:
- Si la bonne réponse est "photosynthèse", une fausse réponse pourrait être "photolyse"
- Si la bonne réponse est "1789", de fausses réponses pourraient être "1792", "1799", "1804"
- Si la bonne réponse est "Paris", de fausses réponses pourraient être "Lyon", "Marseille", "Toulouse"

Réponds uniquement avec les 3 distracteurs, un par ligne, sans numérotation ni formatage.`
}

/**
 * Parse the response text to extract distractors
 */
function parseDistractors(text: string): string[] {
  const lines = text
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .filter(line => !line.match(/^\d+[.)]/)) // Remove numbered lines
    .filter(line => !line.startsWith('-')) // Remove bullet points
    .slice(0, 3) // Take only first 3

  // If we don't have exactly 3, pad with generic options
  while (lines.length < 3) {
    lines.push(`Option ${lines.length + 1}`)
  }

  return lines.slice(0, 3)
}

/**
 * Generate distractors using Google GenAI SDK (Cloudflare Workers compatible)
 */
export async function generateDistractors(
  ai: GoogleGenAI,
  input: DistractorInput,
): Promise<DistractorOutput> {
  try {
    const response = await ai.models.generateContent({
      model: getGeminiModelName(),
      contents: buildPrompt(input),
      config: {
        temperature: 0.7, // Some creativity but not too random
        maxOutputTokens: 200, // Keep responses concise
        topP: 0.9,
        topK: 40,
      },
    })

    const text = response.text
    if (!text) {
      throw new Error('No text received from Gemini')
    }

    const distractors = parseDistractors(text)

    return {
      distractors,
      reasoning: 'Generated by Gemini AI',
    }
  }
  catch (error) {
    console.error('Error generating distractors with Gemini:', error)
    throw new Error(`Failed to generate distractors: ${error instanceof Error ? error.message : 'Unknown error'}`)
  }
}

/**
 * Create a cache key for distractor requests
 */
export function createCacheKey(input: DistractorInput): string {
  // Create a deterministic hash of the input
  const content = `${input.question}|${input.correctAnswer}|${input.subject}|${input.difficulty}|${input.cardType}`

  // Simple hash function (for production, consider using crypto.subtle.digest)
  let hash = 0
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash // Convert to 32-bit integer
  }

  return `distractors:${Math.abs(hash).toString(36)}`
}
